
SELECT 'ACTUALVALUE' AS TABLE_NAME, COUNT(*) AS ROW_COUNT FROM FCD_090_DB_DEV.PROJECT_CASHFLOW_DATA.ACTUALVALUE;
SELECT 'PLANNEDVALUE' AS TABLE_NAME, COUNT(*) AS ROW_COUNT FROM FCD_090_DB_DEV.PROJECT_CASHFLOW_DATA.PLANNEDVALUE;
SELECT 'FORECASTVALUE' AS TABLE_NAME, COUNT(*) AS ROW_COUNT FROM FCD_090_DB_DEV.PROJECT_CASHFLOW_DATA.FORECASTVALUE;
SELECT 'COMBINED_CURVES' AS TABLE_NAME, COUNT(*) AS ROW_COUNT FROM FCD_090_DB_DEV.PROJECT_CASHFLOW_DATA.COMBINED_CURVES;

SELECT 'ACTUALVALUE' AS TABLE_NAME, COUNT(DISTINCT PROJECT_NUMBER || '-' || STAGE || '-' || SUB_STAGE) AS UNIQUE_KEYS FROM FCD_090_DB_DEV.PROJECT_CASHFLOW_DATA.ACTUALVALUE;
SELECT 'PLANNEDVALUE' AS TABLE_NAME, COUNT(DISTINCT PROJECT_NUMBER || '-' || STAGE || '-' || SUB_STAGE) AS UNIQUE_KEYS FROM FCD_090_DB_DEV.PROJECT_CASHFLOW_DATA.PLANNEDVALUE;
SELECT 'FORECASTVALUE' AS TABLE_NAME, COUNT(DISTINCT PROJECT_NUMBER || '-' || STAGE || '-' || SUB_STAGE) AS UNIQUE_KEYS FROM FCD_090_DB_DEV.PROJECT_CASHFLOW_DATA.FORECASTVALUE;

SELECT PROJECT_NUMBER, STAGE, SUB_STAGE FROM FCD_090_DB_DEV.PROJECT_CASHFLOW_DATA.ACTUALVALUE
MINUS
SELECT PROJECT_NUMBER, STAGE, SUB_STAGE FROM FCD_090_DB_DEV.PROJECT_CASHFLOW_DATA.PLANNEDVALUE;

SELECT PROJECT_NUMBER, STAGE, SUB_STAGE FROM FCD_090_DB_DEV.PROJECT_CASHFLOW_DATA.PLANNEDVALUE
MINUS
SELECT PROJECT_NUMBER, STAGE, SUB_STAGE FROM FCD_090_DB_DEV.PROJECT_CASHFLOW_DATA.ACTUALVALUE;

-- QC for Source Tables
-- Row counts for source tables
SELECT 'UNIFIER__Z_BP_INVOICE' AS TABLE_NAME, COUNT(*) AS ROW_COUNT FROM LANDING_DB.FCD_UNIFIER.UNIFIER__Z_BP_INVOICE;
SELECT 'UNIFIER__Z_BP_PAYAPP' AS TABLE_NAME, COUNT(*) AS ROW_COUNT FROM LANDING_DB.FCD_UNIFIER.UNIFIER__Z_BP_PAYAPP;
SELECT 'UNIFIER__Z_BP_PAYREQ' AS TABLE_NAME, COUNT(*) AS ROW_COUNT FROM LANDING_DB.FCD_UNIFIER.UNIFIER__Z_BP_PAYREQ;
SELECT 'UNIFIER__Z_CBS_PRJ_DETAIL' AS TABLE_NAME, COUNT(*) AS ROW_COUNT FROM LANDING_DB.FCD_UNIFIER.UNIFIER__Z_CBS_PRJ_DETAIL;
SELECT 'P6_SCHEDULE' AS TABLE_NAME, COUNT(*) AS ROW_COUNT FROM FCD_090_DB.HCFCD_PROJ_COSTSCHED.P6_SCHEDULE;
SELECT 'NORM_BRGSPENDINGCURVES_SUBSTAGE_0_TO_1' AS TABLE_NAME, COUNT(*) AS ROW_COUNT FROM FCD_090_DB.CDBGPROGRAM.NORM_BRGSPENDINGCURVES_SUBSTAGE_0_TO_1;

-- Unique key counts for source tables (where applicable)
SELECT 'UNIFIER__Z_BP_INVOICE' AS TABLE_NAME, COUNT(DISTINCT PROJECTID) AS UNIQUE_PROJECTS FROM LANDING_DB.FCD_UNIFIER.UNIFIER__Z_BP_INVOICE;
SELECT 'UNIFIER__Z_BP_PAYAPP' AS TABLE_NAME, COUNT(DISTINCT UNIFIER_PROJECT_ID) AS UNIQUE_PROJECTS FROM LANDING_DB.FCD_UNIFIER.UNIFIER__Z_BP_PAYAPP;
SELECT 'UNIFIER__Z_BP_PAYREQ' AS TABLE_NAME, COUNT(DISTINCT PROJECT_ID) AS UNIQUE_PROJECTS FROM LANDING_DB.FCD_UNIFIER.UNIFIER__Z_BP_PAYREQ;
SELECT 'UNIFIER__Z_CBS_PRJ_DETAIL' AS TABLE_NAME, COUNT(DISTINCT PROJECT_NUMBER) AS UNIQUE_PROJECTS FROM LANDING_DB.FCD_UNIFIER.UNIFIER__Z_CBS_PRJ_DETAIL;
SELECT 'P6_SCHEDULE' AS TABLE_NAME, COUNT(DISTINCT PROJECTID) AS UNIQUE_PROJECTS FROM FCD_090_DB.HCFCD_PROJ_COSTSCHED.P6_SCHEDULE;
SELECT 'NORM_BRGSPENDINGCURVES_SUBSTAGE_0_TO_1' AS TABLE_NAME, COUNT(DISTINCT SUBSTAGES) AS UNIQUE_SUBSTAGES FROM FCD_090_DB.CDBGPROGRAM.NORM_BRGSPENDINGCURVES_SUBSTAGE_0_TO_1;

-- Counts by PROJECT_NUMBER for output tables
SELECT 'ACTUALVALUE' AS TABLE_NAME, PROJECT_NUMBER, COUNT(*) AS ROW_COUNT FROM FCD_090_DB_DEV.PROJECT_CASHFLOW_DATA.ACTUALVALUE GROUP BY PROJECT_NUMBER;
SELECT 'PLANNEDVALUE' AS TABLE_NAME, PROJECT_NUMBER, COUNT(*) AS ROW_COUNT FROM FCD_090_DB_DEV.PROJECT_CASHFLOW_DATA.PLANNEDVALUE GROUP BY PROJECT_NUMBER;
SELECT 'FORECASTVALUE' AS TABLE_NAME, PROJECT_NUMBER, COUNT(*) AS ROW_COUNT FROM FCD_090_DB_DEV.PROJECT_CASHFLOW_DATA.FORECASTVALUE GROUP BY PROJECT_NUMBER;
SELECT 'COMBINED_CURVES' AS TABLE_NAME, PROJECT_NUMBER, COUNT(*) AS ROW_COUNT FROM FCD_090_DB_DEV.PROJECT_CASHFLOW_DATA.COMBINED_CURVES GROUP BY PROJECT_NUMBER;
